project:
  type: website
  
execute: 
  freeze: auto
  

website:
  title: "Formation sparklyr"
  navbar:
    left:
      - href: slides.qmd
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

