project:
  type: website
  
execute: 
  freeze: auto
  

website:
  title: "Formation sparklyr"
  
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: index.qmd
        text: Introduction
      - href: slides_v.qmd
        text: Slides
      - href: configuration.qmd
        text: 'Configuration'
      - href: dates.qmd
        text: 'Les dates avec sparklyr'
      - href: oom.qmd
        text: 'Out of memory : help !'
      - href: errors.qmd
        text: 'Guide des erreurs'
      - href: bonnes_pratiques.qmd
        text: 'Bonnes pratiques'
      - href: ressources.qmd
        text: Ressources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

