---
title: "Configuration"
---

# Sur le cluster

Il est nécessaire de configurer la session spark pour établir une connexion entre la session R et un cluster spark (appelée spark connection). Les paramètres à définir sont :

-   Les ressources physiques utilisées :

    1.  par le driver : avec **spark.driver.memory**

    2.  par chaque worker avec **spark.executor.memory** et **spark.executor.cores**

    3.  le nombre de worker avec **spark.executor.instances**


-   la limite de taille des résulats qui peuvent être collectés par le driver avec **spark.driver.maxResultSize. 0 correspond à l'absence de limite.**

## Configuration à utiliser

Cette configuration a été testée dans des opérations de benchmark très lourdes : elle n'est pas limitante dans les traitements de la totalité des données Midas.

```{r}
#| eval: false
#| echo: true

library(sparklyr)
library(tidyverse)

# Fichier de configuration Spark

conf <- spark_config()

conf["spark.driver.memory"] <- "16g"                          
conf$spark.driver.maxResultSize <- 0
conf["spark.executor.cores"] <- 2                             
conf["spark.executor.memory"] <- "12g"
conf["spark.executor.memoryOverhead"] <- "5g"
conf["spark.executor.instances"] <- 5
conf["spark.default.parallelism"] <- 20
conf["spark.sql.shuffle.partitions"] <- 200
conf["spark.sql.adaptive.enabled"] <- "true"
conf["spark.sql.adaptive.coalescePartitions.enabled"] <- "true"
conf["spark.sql.adaptive.localShuffleReader.enabled"] <- "true"
conf["spark.sql.adaptive.skewJoin.enabled"] <- "true"
conf["spark.sql.adaptive.skewJoin.skewedPartitionFactor"] <- 2
conf["spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes"] <- 64L * 1024L^2
conf["spark.locality.wait"] <- "1s"
sc <- spark_connect(master = "yarn", config = conf)
```
::: callout-important
## Temps de connexion

Pour se connecter au cluster, il faut environ 5 minutes, à chaque connexion. Spark cluster n'est pas du tout adapté à des traitements légers (moins de 10 minutes).
:::